### ISSUE TITLE
local storage 내 변조 문제

### ISSUE THREAD

**Issue by kysth0707** [Astro-Chaser/Server-AstroChaser#147]
local storage 내 값들은 새로고침 할 때 accessJWT 를 토대로 정보가 설정되는 것으로 보입니다.
즉, 새로고침 없이는 변조가 가능한 것으로 보입니다.

![image](https://user-images.githubusercontent.com/83905675/189684178-1b290297-b05f-4893-a8a8-bb08ebe6ae15.png)
member 를 운영진으로 변경 후, 새로고침 없이 작성을 클릭하면 뚫립니다

local storage 내에 유저의 기본 정보와 권한을 저장하는 것보다,
local storage 내에 accessJWT 만 남겨두고 모든 유저 API 관련 요청할 때, accessJWT 도 같이 받아서
해당 값으로 서버 측에서 전부 처리하는 것이 안전할 거 같습니다.

**Comment by BUZZINGPolarBear** [comment]
local storage 변조가 가능한지 몰랐어요.. 완전 무지했습니다.
서버측 부하를 줄여보려고 local storage에 사이트에 필요한 정보만 추려서 jwt 해독 결과를 넣어놨었는데, 잘못된 설계였네요.
서버단에서 항상 jwt verify하고, 권한 부여하도록 하겠습니다.
감사합니다!

**Comment by kysth0707** [comment]
넵!

**Comment by BUZZINGPolarBear** [comment]
글 작성 페이지 접속할때와 게시글 등록 버튼을 누를 때 둘다 jwt인증을 하도록 하고, 신분을 확인하도록하였습니다!
